# Prometheus Scraper Config
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'bike_auction_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
